name:                morse
version:             0.1.0.0
github:              "glebec/morse"
license:             BSD3
author:              "Gabriel Lebec"
maintainer:          "glebec@gmail.com"
copyright:           "2018 Gabriel Lebec"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/glebec/morse#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- QuickCheck

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -fwarn-tabs

executables:
  morse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse

tests:
  morse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse
